[2024-12-26T16:03:23.814+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-26T16:03:23.832+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: train_and_retrain_xgboost_pipeline.check_drift_and_retrain manual__2024-12-26T16:03:17.503848+00:00 [queued]>
[2024-12-26T16:03:23.845+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: train_and_retrain_xgboost_pipeline.check_drift_and_retrain manual__2024-12-26T16:03:17.503848+00:00 [queued]>
[2024-12-26T16:03:23.847+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2024-12-26T16:03:23.864+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): check_drift_and_retrain> on 2024-12-26 16:03:17.503848+00:00
[2024-12-26T16:03:23.871+0000] {standard_task_runner.py:72} INFO - Started process 1012 to run task
[2024-12-26T16:03:23.875+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'train_and_retrain_xgboost_pipeline', 'check_drift_and_retrain', 'manual__2024-12-26T16:03:17.503848+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/train_xgboost_pipeline.py', '--cfg-path', '/tmp/tmpb64b_970']
[2024-12-26T16:03:23.879+0000] {standard_task_runner.py:105} INFO - Job 13: Subtask check_drift_and_retrain
[2024-12-26T16:03:23.896+0000] {logging_mixin.py:190} WARNING - /usr/local/lib/python3.10/site-packages/***/settings.py:209 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-12-26T16:03:23.934+0000] {task_command.py:467} INFO - Running <TaskInstance: train_and_retrain_xgboost_pipeline.check_drift_and_retrain manual__2024-12-26T16:03:17.503848+00:00 [running]> on host 42dc6dafdabb
[2024-12-26T16:03:24.016+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='train_and_retrain_xgboost_pipeline' AIRFLOW_CTX_TASK_ID='check_drift_and_retrain' AIRFLOW_CTX_EXECUTION_DATE='2024-12-26T16:03:17.503848+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-26T16:03:17.503848+00:00'
[2024-12-26T16:03:24.018+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-26T16:03:24.033+0000] {train_xgboost_pipeline.py:437} INFO - Starting drift detection and retraining if necessary...
[2024-12-26T16:03:24.113+0000] {train_xgboost_pipeline.py:313} INFO - Downloaded data/Ingestion/Financial_with_Sentiment.csv from MinIO to /tmp/Financial_with_Sentiment.csv
[2024-12-26T16:03:24.186+0000] {train_xgboost_pipeline.py:313} INFO - Downloaded data/Ingestion/Financial_with_Sentiment_pseudo.csv from MinIO to /tmp/Financial_with_Sentiment_pseudo.csv
[2024-12-26T16:03:24.544+0000] {logging_mixin.py:190} WARNING - /app/dags/train_xgboost_pipeline.py:448 DtypeWarning: Columns (2161) have mixed types. Specify dtype option on import or set low_memory=False.
[2024-12-26T16:03:24.991+0000] {logging_mixin.py:190} WARNING - /app/dags/train_xgboost_pipeline.py:449 DtypeWarning: Columns (2161) have mixed types. Specify dtype option on import or set low_memory=False.
[2024-12-26T16:03:25.056+0000] {logging_mixin.py:190} WARNING - /app/dags/train_xgboost_pipeline.py:404 SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
[2024-12-26T16:03:26.405+0000] {logging_mixin.py:190} WARNING - /app/dags/train_xgboost_pipeline.py:404 SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
[2024-12-26T16:03:26.414+0000] {train_xgboost_pipeline.py:460} INFO - Drift detection result: Forced to True for testing.
[2024-12-26T16:03:26.416+0000] {train_xgboost_pipeline.py:464} INFO - Drift detected! Retraining the model...
[2024-12-26T16:03:26.747+0000] {train_xgboost_pipeline.py:475} INFO - Retrained Model Evaluation - MSE: 200.63, R2: -0.02
[2024-12-26T16:03:26.748+0000] {logging_mixin.py:190} INFO - Retrained Model Metrics:
MSE: 200.63
R2: -0.02
[2024-12-26T16:03:26.749+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-12-26T16:03:26.758+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-26T16:03:26.758+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=train_and_retrain_xgboost_pipeline, task_id=check_drift_and_retrain, run_id=manual__2024-12-26T16:03:17.503848+00:00, execution_date=20241226T160317, start_date=20241226T160323, end_date=20241226T160326
[2024-12-26T16:03:26.783+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-12-26T16:03:26.798+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-26T16:03:26.802+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
