[2024-12-28T12:19:15.557+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-28T12:19:15.582+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: xgboost_drift_pipeline.retrain_model manual__2024-12-28T12:19:09.021546+00:00 [queued]>
[2024-12-28T12:19:15.593+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: xgboost_drift_pipeline.retrain_model manual__2024-12-28T12:19:09.021546+00:00 [queued]>
[2024-12-28T12:19:15.595+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2024-12-28T12:19:15.611+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): retrain_model> on 2024-12-28 12:19:09.021546+00:00
[2024-12-28T12:19:15.619+0000] {standard_task_runner.py:72} INFO - Started process 341 to run task
[2024-12-28T12:19:15.622+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'xgboost_drift_pipeline', 'retrain_model', 'manual__2024-12-28T12:19:09.021546+00:00', '--job-id', '42', '--raw', '--subdir', 'DAGS_FOLDER/train_xgboost_pipeline.py', '--cfg-path', '/tmp/tmpogjcki32']
[2024-12-28T12:19:15.625+0000] {standard_task_runner.py:105} INFO - Job 42: Subtask retrain_model
[2024-12-28T12:19:15.642+0000] {logging_mixin.py:190} WARNING - /usr/local/lib/python3.10/site-packages/***/settings.py:209 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-12-28T12:19:15.679+0000] {task_command.py:467} INFO - Running <TaskInstance: xgboost_drift_pipeline.retrain_model manual__2024-12-28T12:19:09.021546+00:00 [running]> on host 42dc6dafdabb
[2024-12-28T12:19:15.776+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='xgboost_drift_pipeline' AIRFLOW_CTX_TASK_ID='retrain_model' AIRFLOW_CTX_EXECUTION_DATE='2024-12-28T12:19:09.021546+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-28T12:19:09.021546+00:00'
[2024-12-28T12:19:15.778+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-28T12:19:15.793+0000] {train_xgboost_pipeline.py:802} INFO - Starting retraining process...
[2024-12-28T12:19:15.821+0000] {train_xgboost_pipeline.py:674} INFO - Downloaded data/Ingestion/Financial_with_Sentiment_pseudo.csv from MinIO to /tmp/Financial_with_Sentiment_pseudo.csv
[2024-12-28T12:19:15.835+0000] {logging_mixin.py:190} WARNING - /app/dags/train_xgboost_pipeline.py:694 SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
[2024-12-28T12:19:16.031+0000] {train_xgboost_pipeline.py:679} INFO - Uploaded /tmp/retrained_model_test.pkl to MinIO at data/Ingestion/retrained_model_test.pkl
[2024-12-28T12:19:16.031+0000] {train_xgboost_pipeline.py:827} INFO - Retrained model saved and uploaded.
[2024-12-28T12:19:16.039+0000] {train_xgboost_pipeline.py:833} INFO - Retrained Model Evaluation - MSE: 2562.47, R2: -0.46
[2024-12-28T12:19:16.040+0000] {logging_mixin.py:190} INFO - Retrained Model Metrics:
MSE: 2562.47
R2: -0.46
[2024-12-28T12:19:16.040+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-12-28T12:19:16.049+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-28T12:19:16.050+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=xgboost_drift_pipeline, task_id=retrain_model, run_id=manual__2024-12-28T12:19:09.021546+00:00, execution_date=20241228T121909, start_date=20241228T121915, end_date=20241228T121916
[2024-12-28T12:19:16.077+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-12-28T12:19:16.097+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-12-28T12:19:16.100+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
